interface TranslationRequirements {
    it: string
    zh: string // 添加简体中文支持
}

interface Credits {
    username: string,
    githubLink: string
}


export let languageCredits = new Map<string, Credits>([
    ["it", {username: "dinoosauro", githubLink: "https://github.com/dinoosauro"}],
    ["en", {username: "dinoosauro", githubLink: "https://github.com/dinoosauro"}],
    ["zh", {username: "God-2077", githubLink: "https://github.com/God-2077"}],
])

let translations = new Map<string, TranslationRequirements>([
    ["The background color", { it: "Il colore dello sfondo", zh: "背景颜色" }],
    ["A background image", { it: "Una immagine come sfondo", zh: "背景图片" }],
    ["A local video", { it: "Un video locale", zh: "本地视频" }],
    ["A YouTube embed", { it: "Un video di YouTube", zh: "YouTube 嵌入" }],
    ["Add content", { it: "Aggiungi contenuto", zh: "添加内容" }],
    ["Delete content", { it: "Rimuovi contenuto", zh: "删除内容" }],
    ["Write a YouTube Playlist or Video URL:", { it: "Scrivi l'URL del video o della playlist di YouTube", zh: "输入 YouTube 播放列表或视频 URL：" }],
    ["Apply URL", { it: "Applica URL", zh: "应用 URL" }],
    ["Blur", { it: "Blur", zh: "模糊" }],
    ["Brightness", { it: "Luminosità", zh: "亮度" }],
    ["Add blur effect also to cards (experimental; can greatly slow down ffmpeg-web)", { it: "Aggiungi l'effetto blur anche alle card (sperimentale; può rallentare di molto ffmpeg-web)", zh: "同时对卡片应用模糊效果（实验性；可能显著降低 ffmpeg-web 速度）" }],
    ["Settings", { it: "Impostazioni", zh: "设置" }],
    ["FFmpeg settings:", { it: "Impostazioni di FFmpeg:", zh: "FFmpeg 设置：" }],
    ["Use the following FFmpeg version:", { it: "Usa la seguente versione di FFmpeg:", zh: "使用以下 FFmpeg 版本：" }],
    ["Suggested", { it: "Consigliato", zh: "推荐" }],
    ["Might not work on all codecs", { it: "Potrebbe non funzionare con tutti i codec", zh: "可能不适用于所有编解码器" }],
    ["Enable multithreaded version of FFmpeg WebAssembly", { it: "Usa la versione multi-threaded di FFmpeg", zh: "启用 FFmpeg WebAssembly 多线程版本" }],
    ["File output:", { it: "File di destinazione:", zh: "文件输出：" }],
    ["Use the File System API", { it: "Usa la File System API", zh: "使用文件系统 API" }],
    ["Save using a link", { it: "Salva utilizzando un link", zh: "使用链接保存" }],
    ["Save as a zip file", { it: "Salva come file zip", zh: "保存为 zip 文件" }],
    ["Hardware acceleration", { it: "Accelerazione hardware", zh: "硬件加速" }],
    ["Add arguments before the FFmpeg script to allow hardware acceleration. You can find presets for most hardware acceleration providers in the select below.", { it: "Aggiungi argomenti prima dello script di FFmpeg per utilizzare l'accelerazione hardware. Puoi trovare dei presets per la maggior parte dei fornitori di schede video con accelerazione hardware dal menù di selezione in basso.", zh: "在 FFmpeg 脚本前添加参数以启用硬件加速。您可以在下方选择框中找到大多数硬件加速供应商的预设。" }],
    ["No hardware acceleration", { it: "Nessuna accelerazione hardware", zh: "无硬件加速" }],
    ["Custom syntax", { it: "Sintassi personalizzata", zh: "自定义语法" }],
    ["Custom arguments:", { it: "Argomenti personalizzati:", zh: "自定义参数：" }],
    ["You can write custom arguments, that will be put at the start of the ffmpeg script, here.", { it: "Puoi scrivere qui degli argomenti personalizzati da inserire all'inizio dello script di FFmpeg", zh: "您可以在此处编写自定义参数，这些参数将放在 ffmpeg 脚本的开头" }],
    ["UI Customization:", { it: "Personalizzazione dell'interfaccia:", zh: "界面自定义：" }],
    ["Create a new theme:", { it: "Crea un nuovo tema:", zh: "创建新主题：" }],
    ["You can find all the values you need to edit here. Make sure to save the theme before unloading the page!", { it: "Qui trovi tutti i valori che puoi modificare. Ricordati di salvare il tema prima di chiudere la pagina!", zh: "您可以在此处找到所有需要编辑的值。请确保在卸载页面之前保存主题！" }],
    ["Save theme", { it: "Salva tema", zh: "保存主题" }],
    ["Manage current themes", { it: "Gestisci i temi correnti", zh: "管理当前主题" }],
    ["Background content:", { it: "Contenuto nello sfondo:", zh: "背景内容：" }],
    ["Use as background:", { it: "Utilizza come sfondo:", zh: "用作背景：" }],
    ["Screensaver:", { it: "Salvaschermo:", zh: "屏幕保护程序：" }],
    ["Enable screensaver", { it: "Abilita salvaschermo", zh: "启用屏幕保护程序" }],
    ["Enable screensaver after", { it: "Abilita salvaschermo dopo", zh: "在以下时间后启用屏幕保护程序" }],
    ["Screensaver background:", { it: "Sfondo del salvaschermo:", zh: "屏幕保护程序背景：" }],
    ["Available content in the screensaver:", { it: "Contenuto disponibile nel salvaschermo:", zh: "屏幕保护程序中可用的内容：" }],
    ["Show file name", { it: "Mostra il nome del file", zh: "显示文件名" }],
    ["Show conversion progress and console output", { it: "Mostra il progresso della conversione e l'output della console", zh: "显示转换进度和控制台输出" }],
    ["Enable screensaver in fullscreen mode", { it: "Abilita salvaschermo in modalità a schermo interno", zh: "在全屏模式下启用屏幕保护程序" }],
    ["Enable screensaver now", { it: "Abilita adesso il salvaschermo", zh: "立即启用屏幕保护程序" }],
    ["Enable alerts", { it: "Abilita avvisi", zh: "启用通知" }],
    ["Close alert after", { it: "Chiudi avviso dopo", zh: "在以下时间后关闭通知" }],
    ["Reset ignored alerts", { it: "Reimposta gli avvisi ignorati", zh: "重置已忽略的通知" }],
    ["Advanced file save preferences:", { it: "Preferenze avanzate per il salvataggio dei file:", zh: "高级文件保存首选项：" }],
    ["Keep Blobs saved", { it: "Mantieni salvati i Blob", zh: "保留 Blob 保存" }],
    ["Immediately delete Blobs after download. Disable this if you aren't able to download files", { it: "Elimina immediatamente i Blob dopo il download. Disabilita quest'opzione se hai problemi nello scaricare i file", zh: "下载后立即删除 Blob。如果您无法下载文件，请禁用此选项" }],
    ["Save conversion preferences", { it: "Salva le preferenze di conversione", zh: "保存转换首选项" }],
    ["Custom input:", { it: "Input personalizzato:", zh: "自定义输入：" }],
    [`Write an argument in the textbox below. Then, click "Add" or press "Tab" to add it as an argument. Click on each argument to delete it.`, { it: `Scrivi un argomento nella casella di testo in basso. Poi clicca su "Aggiungi" oppure premi "Tab" per aggiungerlo come argomento. Clicca su qualsiasi argomento per eliminarlo`, zh: `在下方文本框中输入参数。然后点击"添加"或按"Tab"键将其添加为参数。点击任意参数可删除它` }],
    ["You can also add", { it: "Puoi anche aggiungere", zh: "您也可以添加" }],
    ["that'll be automatically replaced with the file name, and", { it: "che verrà automaticamente sostituito con il nome del file, e", zh: "这将自动替换为文件名，以及" }],
    ["to add a dollar sign.", { it: "per aggiungere il segno del dollaro.", zh: "用于添加美元符号" }],
    ["Merge files:", { it: "Unisci file:", zh: "合并文件：" }],
    ["Files will be merged without re-encoding. Write the output file name, with its extension, below.", { it: "I file vengono uniti senza ricodifica. Scrivi il nome del file finale, con la sua estensione, qui in basso.", zh: "文件将无需重新编码即可合并。在下方输入输出文件名及其扩展名" }],
    ["Keep the album art (or the thumbnail) of the first file. Disable it if there are issues with the conversion.", { it: "Mantieni la copertina (o la miniatura) del primo file. Disabilita se ci sono problemi nella conversione", zh: "保留第一个文件的专辑封面（或缩略图）。如果转换出现问题，请禁用它" }],
    ["Convert image(s):", { it: "Converti immagini:", zh: "转换图像：" }],
    ["You can convert images to various output formats. You can apply the same filters as the video part", { it: "Puoi convertire le immagini a diversi formati di output. Puoi usare gli stessi filtri del contenuto video.", zh: "您可以将图像转换为各种输出格式。您可以应用与视频部分相同的滤镜" }],
    ["Image output format:", { it: "Formato dell'immagine finale:", zh: "图像输出格式：" }],
    ["Add metadata:", { it: "Aggiungi metadati:", zh: "添加元数据：" }],
    ["You can edit metadata tags directly from FFmpeg, without re-encoding the file. Choose the metadata from the next tab.", { it: "Puoi modificare i metadati direttamente da FFmpeg, senza ricodificare il file. Scegli i metadati dalla prossima sezione.", zh: "您可以直接通过 FFmpeg 编辑元数据标签，无需重新编码文件。请从下一个选项卡中选择元数据" }],
    ["Keep current metadata", { it: "Mantieni i metadati correnti", zh: "保留当前元数据" }],
    ["Keep album art in MP4 files, disabling custom tags", { it: "Mantieni la copertina nei file MP4, disabilitando i tag personalizzati", zh: "在 MP4 文件中保留专辑封面，禁用自定义标签" }],
    ["Audio output:", { it: "Output dell'audio:", zh: "音频输出：" }],
    ["Audio channels:", { it: "Canali audio:", zh: "音频通道：" }],
    ["Default", { it: "Predefinito", zh: "默认" }],
    ["Mono", { it: "Mono", zh: "单声道" }],
    ["Stereo", { it: "Stereo", zh: "立体声" }],
    ["Keep album art", { it: "Mantieni la copertina", zh: "保留专辑封面" }],
    ["Copy all the metadata at the end. Enable this only if FFmpeg, by default, has discarded some metadata. This applies both for video and audio formats.", { it: "Copia tutti i metadati alla fine. Abilita questo solo se FFmpeg, di default, ha eliminato alcuni metadati. Questo viene applicato sia ai formati video che ai formati audio.", zh: "在最后复制所有元数据。仅当 FFmpeg 默认丢弃了某些元数据时才启用此功能。这适用于视频和音频格式" }],
    ["Add audio filters", { it: "Aggiungi filtri audio", zh: "添加音频滤镜" }],
    ["Audio filters:", { it: "Filtri audio:", zh: "音频滤镜：" }],
    ["Audio volume:", { it: "Volume audio:", zh: "音频音量：" }],
    ["Change loudness: add", { it: "Cambia rumorosità: aggiungi", zh: "更改响度：添加" }],
    ["decibels", { it: "decibel", zh: "分贝" }],
    ["Noise removal:", { it: "Rimozione del rumore:", zh: "降噪：" }],
    ["Remove noise:", { it: "Rimuovi rumore:", zh: "移除噪声：" }],
    ["Custom audio filter:", { it: "Filtro audio personalizzato:", zh: "自定义音频滤镜：" }],
    ["Apply a custom audio filter that follows the FFmpeg syntax:", { it: "Applica un filtro audio personalizzato che segue la sintassi di FFmpeg", zh: "应用遵循 FFmpeg 语法的自定义音频滤镜：" }],
    ["Choose bitrate:", { it: "Scegli bitrate:", zh: "选择比特率：" }],
    ["Choose with a slider", { it: "Scegli con uno slider:", zh: "使用滑块选择" }],
    ["Closer to the left:", { it: "Più vicino a sinistra:", zh: "靠近左侧：" }],
    ["higher quality", { it: "qualità più alta", zh: "更高质量" }],
    ["worse quality", { it: "qualità più bassa", zh: "更低质量" }],
    ["high bitrate", { it: "bitrate più alto", zh: "更高比特率" }],
    ["Conversion status:", { it: "Status della conversione:", zh: "转换状态：" }],
    ["You'll see here all the logs made by ffmpeg.", { it: "Vedrai qui tutti i log fatti da FFmpeg", zh: "您将在此处看到 ffmpeg 生成的所有日志" }],
    ["File selection:", { it: "Selezione dei file:", zh: "文件选择：" }],
    ["Choose files:", { it: "Scegli file:", zh: "选择文件：" }],
    ["Choose how multiple files should be managed:", { it: "Scegli come i file multipli dovrebbero essere gestiti", zh: "选择应如何管理多个文件：" }],
    ["Use only the first file", { it: "Usa solo nel primo file", zh: "仅使用第一个文件" }],
    ["Add all the files in the output argument", { it: "Aggiungi tutti i file nell'argomento di output", zh: "将所有文件添加到输出参数中" }],
    ["Add the video/audio if it has the same name as the first file", { it: "Aggiungi il video/audio se ha lo stesso nome del primo file", zh: "如果视频/音频与第一个文件同名，则添加它" }],
    ["Add the video/audio if it has the same name (for each content)", { it: "Aggiungi il video/audio se ha lo stesso nome (per ogni file)", zh: "如果视频/音频同名（针对每个内容），则添加它" }],
    ["Execute the same command for each file", { it: "Esegui lo stesso comando per ogni file", zh: "对每个文件执行相同的命令" }],
    ["Note: the selected files will be overwritten. Please make a copy of them before continuing.", { it: "Nota: i file selezionati verranno sovrascritti. Potrebbe essere utile fare una copia dei file prima di continuare.", zh: "注意：所选文件将被覆盖。请继续前备份文件" }],
    ["Select a folder", { it: "Scegli una cartella", zh: "选择文件夹" }],
    ["Choose output directory", { it: "Scegli la directory di desstinazione", zh: "选择输出目录" }],
    ["Choose a folder", { it: "Scegli una cartella", zh: "选择文件夹" }],
    ["Choose a file", { it: "Scegli un file", zh: "选择文件" }],
    ["folder", { it: "cartella", zh: "文件夹" }],
    ["file", { it: "file", zh: "文件" }],
    ["Privacy:", { it: "Privacy:", zh: "隐私：" }],
    ["What do you want to do?", { it: "Cosa vorresti fare?", zh: "您想做什么？" }],
    ["Scroll to see more options", { it: "Scroll per vedere più opzioni", zh: "滚动查看更多选项" }],
    ["Media encoding", { it: "Codifica multimediale", zh: "媒体编码" }],
    ["Custom command", { it: "Comando personalizzato", zh: "自定义命令" }],
    ["Merge content", { it: "Unisci contenuto", zh: "合并内容" }],
    ["Convert to image", { it: "Converti immagini", zh: "转换为图像" }],
    ["Add metadata", { it: "Aggiungi metadati", zh: "添加元数据" }],
    ["If you are re-encoding the media file, you can choose its options. Otherwise, choose the files on the next card", { it: "Se stai ricodificando il file, puoi selezionare le sue opzioni. Oppure, scegli i file nella apposita card", zh: "如果您正在重新编码媒体文件，可以选择其选项。否则，请在下一张卡片上选择文件" }],
    ["You can choose between lots of formats. Click on the switch to select what media type(s) you want in your final file:", { it: "Puoi scegliere tra molti formati. Clicca sullo slider per selezionare quali file multimediali vuoi nel file finale:", zh: "您可以在多种格式之间选择。点击开关选择最终文件中需要的媒体类型：" }],
    ["Enable video source", { it: "Abilita sorgente video", zh: "启用视频源" }],
    ["Enable audio source", { it: "Abilita sorgente audio", zh: "启用音频源" }],
    ["Add metadata:", { it: "Aggiungi metadati:", zh: "添加元数据：" }],
    ["Choose a metadata from the list below, and add its value.", { it: "Scegli un metadato dalla lista in basso, ed scrivi il suo valore.", zh: "从下方列表中选择元数据并添加其值" }],
    ["Custom key", { it: "Chiave personalizzata", zh: "自定义键" }],
    ["Value", { it: "Valore", zh: "值" }],
    ["Add metadata", { it: "Aggiungi metadato", zh: "添加元数据" }],
    ["Added metadata:", { it: "Metadati aggiunti", zh: "已添加元数据：" }],
    ["Delete", { it: "Elimina", zh: "删除" }],
    ["Add custom album art", { it: "Aggiungi copertina personalizzata", zh: "添加自定义专辑封面" }],
    ["Delete every video track (also the source album art)", { it: "Elimina qualsiasi traccia video (anche la copertina d'origine)", zh: "删除每个视频轨道（包括源专辑封面）" }],
    ["Re-download files", { it: "Riscarica file", zh: "重新下载文件" }],
    ["Choose from the select below the files to re-download.", { it: "Scegli dal menù di selezione in basso i file da riscaricare.", zh: "从下方选择框中选择要重新下载的文件" }],
    ["Download file", { it: "Scarica file", zh: "下载文件" }],
    ["Delete Blob from memory", { it: "Elimina il Blob dalla memoria", zh: "从内存中删除 Blob" }],
    ["Trim content:", { it: "Taglia contenuto:", zh: "裁剪内容：" }],
    ["Don't trim content", { it: "Non tagliare il contenuto", zh: "不裁剪内容" }],
    ["Trim content (single timestamp)", { it: "Taglia il contenuto (timestamp singolo)", zh: "裁剪内容（单个时间戳）" }],
    ["Trim content (multiple timestamps)", { it: "Taglia il contenuto (timestamp multipli)", zh: "裁剪内容（多个时间戳）" }],
    ["Single timestamp settings:", { it: "Impostazioni per il singolo timestamp:", zh: "单时间戳设置：" }],
    ["Start:", { it: "Inizio:", zh: "开始：" }],
    ["End:", { it: "Fine:", zh: "结束：" }],
    ["Multiple timestamps settings:", { it: "Impostazioni per i timestamp multipli:", zh: "多时间戳设置：" }],
    ["Write the multiple timestamps, one for each line. Then, add a divider between the timestamp and the file title", { it: "Scrivi i timestamp multipli, uno per riga. Dopo, aggiungi un divisore tra i timestamp ed il titolo dei file", zh: "写入多个时间戳，每行一个。然后在时间戳和文件标题之间添加分隔符" }],
    ["Divider", { it: "Divisore", zh: "分隔符" }],
    ["Timestamp at the left", { it: "Il timestamp è a sinistra", zh: "时间戳在左侧" }],
    ["Automatically add title and track metadata", { it: "Aggiungi automaticamente i metadati del titolo e del numero di traccia", zh: "自动添加标题和轨道元数据" }],
    ["Start from track", { it: "Inizia dalla traccia", zh: "从轨道开始" }],
    ["Image output:", { it: "Output dell'immagine:", zh: "图像输出：" }],
    ["Video output:", { it: "Output del video:", zh: "视频输出：" }],
    ["Keep the same FPS", { it: "Mantieni gli stessi FPS", zh: "保持相同 FPS" }],
    ["FPS Options:", { it: "Opzioni degli FPS:", zh: "FPS 选项：" }],
    ["Input FPS:", { it: "FPS di origine:", zh: "输入 FPS：" }],
    ["Output FPS:", { it: "FPS di destinazione:", zh: "输出 FPS：" }],
    ["Change aspect ratio and rotation settings", { it: "Cambia l'aspect ratio e le impostazioni di rotazione", zh: "更改宽高比和旋转设置" }],
    ["Aspect ratio", { it: "Aspect ratio", zh: "宽高比" }],
    [`Put "-1" as the value to skip it when elaborating arguments`, { it: `Metti "-1" come valore per saltarlo durante l'elaborazione delle preferenze`, zh: `输入"-1"作为值以便在参数处理时跳过` }],
    ["Width:", { it: "Larghezza:", zh: "宽度：" }],
    ["Height:", { it: "Altezza:", zh: "高度：" }],
    ["Rotation:", { it: "Rotazione:", zh: "旋转：" }],
    ["Don't rotate", { it: "Non ruotare", zh: "不旋转" }],
    ["Rotate", { it: "Ruota di", zh: "旋转" }],
    ["Change pixel format:", { it: "Cambia il formato dei pixel:", zh: "更改像素格式：" }],
    ["Write the output pixel format. Leave this field blank to apply the default one", { it: "Scrivi il formato dei pixel di destinazione. Lascia questo campo vuoto per applicare quello di default.", zh: "写入输出像素格式。留空则应用默认格式" }],
    ["Add video filters", { it: "Aggiungi filtri video", zh: "添加视频滤镜" }],
    ["Video filters:", { it: "Filtri video:", zh: "视频滤镜：" }],
    ["Position", { it: "Posizione", zh: "位置" }],
    ["Deinterlace video", { it: "Deinterlaccia video", zh: "去隔行扫描视频" }],
    ["Video filters:", { it: "Filtri video:", zh: "视频滤镜：" }],
    ["Apply one of the following video filters:", { it: "Applica uno dei seguenti filtri video:", zh: "应用以下视频滤镜之一：" }],
    ["Custom video filter:", { it: "Filtro video personalizzato:", zh: "自定义视频滤镜：" }],
    ["Apply a custom video filter that follows the FFmpeg syntax:", { it: "Applica un filtro video personalizzato che segua la sintassi di FFmpeg:", zh: "应用遵循 FFmpeg 语法的自定义视频滤镜：" }],
    ["Conversion text will appear here", { it: "Il testo della conversione apparirà qui", zh: "转换文本将显示在此处" }],
    ["No conversion started", { it: "Nessuna conversione iniziata", zh: "未开始转换" }],
    ["The selected conversion (Conversion", { it: "La conversione selezionata (Conversione", zh: "所选转换（转换" }],
    ["has ended!", { it: "è finita!", zh: "已结束！" }],
    ["Converting file:", { it: "Conversione del file:", zh: "正在转换文件：" }],
    ["Close dialog", { it: "Chiudi pop-up", zh: "关闭对话框" }],
    ["Close", { it: "Chiudi", zh: "关闭" }],
    ["Do not show this again", { it: "Non mostrare più", zh: "不再显示" }],
    ["Started operation", { it: "È iniziata l'operazione", zh: "操作已开始" }],
    [`Change the Operation ID from the "Conversion Status" tab to see the current progress.`, { it: `Cambia l'ID dell'operazione dalla scheda dello "Status di conversione" per vedere il progresso di quest'operazione.`, zh: `在"转换状态"选项卡中更改操作ID以查看当前进度` }],
    ["Completed operation", { it: "È stata completata l'operazione", zh: "操作已完成" }],
    ["Conversion options:", { it: "Opzioni di conversione:", zh: "转换选项：" }],
    ["Alerts", { it: "Avvisi", zh: "通知" }],
    ["Cut video:", { it: "Taglia video:", zh: "剪切视频：" }],
    ["Your media files are locally elaborated, therefore they'll always stay on your device.", { it: "I tuoi file multimediali sono elaborati localmente, e quindi staranno sempre solo sul tuo dispositivo.", zh: "您的媒体文件在本地处理，因此它们始终保留在您的设备上" }],
    ["This website connects to unpkg & Google Fonts only to fetch essential resources to work, and doesn't share any data with them.", { it: "Questo sito si connette ad unpkg e Google Fonts per ottenere risorse essenziali per il suo funzionamento, ma non condivide alcun dato con loro.", zh: "本网站仅连接到 unpkg 和 Google Fonts 以获取必要资源，不与它们共享任何数据" }],
    ["This website is published under the", { it: "Questo sito è disponibile sotto la", zh: "本网站基于" }],
    ["MIT license", { it: "licenza MIT", zh: "MIT 许可证" }],
    ["and you can find (and, if you want, analyze) the", { it: "e puoi trovare (e, se vuoi, analizzare) il", zh: "发布，您可以在 GitHub 上找到（并可分析）" }],
    ["source code on GitHub", { it: "codice sorgente su GitHub", zh: "源代码" }],
    ["Won't replace duplicate (no access to your device's file system)", { it: "Non sostituirà i duplicati (nessun accesso al file system del dispositivo)", zh: "不会替换重复文件（无法访问设备文件系统）" }],
    ["Will replace duplicates (direct access to File System)", { it: "Sostituirà i duplicati (accesso diretto al file system)", zh: "将替换重复文件（直接访问文件系统）" }],
    ["Overwrite", { it: "Sovrascrivi", zh: "覆盖" }],
    ["Found existent file", { it: "Trovate un file già esistente", zh: "发现已存在文件" }],
    ["Exit after each timestamp conversion", { it: "Esci dopo ogni conversione del timestamp", zh: "每个时间戳转换后退出" }],
    ["Exit after each file conversion", { it: "Esci dopo ogni conversione del file", zh: "每个文件转换后退出" }],
    ["Move content from top to bottom (and viceversa) every", { it: "Sposta il contenuto dall'alto verso il basso (e viceversa) ogni", zh: "每隔指定时间将内容从顶部移动到底部（反之亦然）" }],
    ["Convert only files that ends with (separate multiple extension with |):", { it: "Converti solamente i file che finiscono con (separa più estensioni con |):", zh: "仅转换以以下结尾的文件（多个扩展名用 | 分隔）：" }],
    ["Installation", { it: "Installazione", zh: "安装" }],
    ["You can install ffmpeg-web as a Progressive Web App, or you can get way higher performances by installing the Electron application. You can find the instructions from the Select below", { it: "Puoi installare ffmpeg-web come una Progressive Web App, o puoi ottenere prestazioni molto più elevate installando l'applicazione Electron. Puoi trovare le istruzioni dal selettore in basso", zh: "您可以将 ffmpeg-web 安装为渐进式 Web 应用，或通过安装 Electron 应用获得更高性能。您可以从下方选择框中找到说明" }],
    ["Download the zip file of the repository:", { it: "Scarica il file zip della repository:", zh: "下载仓库的 zip 文件：" }],
    ["click here", { it: "clicca qui", zh: "点击此处" }],
    ["Extract the files, and make sure to have Node.JS 20 and a native version of FFmpeg installed", { it: "Estrai i file, ed assicurati di aver installato Node.JS 20 e una versione nativa di FFmpeg", zh: "解压文件，并确保已安装 Node.JS 20 和原生 FFmpeg 版本" }],
    ["Run the following command to install the app:", { it: "Esegui il seguente comando per installare l'app:", zh: "运行以下命令安装应用：" }],
    ["And that's done! You can now run the app by writing", { it: "Ed hai finito! Puoi ora eseguire l'app scrivendo", zh: "完成！您现在可以通过输入以下命令运行应用：" }],
    ["from the command line in that folder", { it: "dalla linea di comando in quella cartella", zh: "在该文件夹的命令行中" }],
    [`click on the three dots near the URL bar, and then on "Install as an app"`, { it: `Clicca sui tre puntini vicino alla barra degli URL, e clicca su "Installa come app"`, zh: `点击 URL 栏附近的三个点，然后点击"安装为应用"` }],
    [`click on the "Install app" icon at the right of the URL address`, { it: `clicca sull'icona "Installa applicazione" a destra dell'URL`, zh: `点击 URL 地址右侧的"安装应用"图标` }],
    [`share the webpage, and then click on "Add to the home"`, { it: `condividi la pagina, e poi clicca su "Aggiungi alla schermata home"`, zh: `共享网页，然后点击"添加到主屏幕"` }],
    ["About this website", { it: "Su questo sito", zh: "关于本网站" }],
    ["View on GitHub", { it: "Visualizza su GitHub", zh: "在 GitHub 上查看" }],
    ["Show installation instructions", { it: "Mostra istruzioni di installazione", zh: "显示安装说明" }],
    ["Hide this card", { it: "Nascondi questa card", zh: "隐藏此卡片" }],
    ["Show update changelog", { it: "Mostra il changelog degli aggiornamenti", zh: "显示更新日志" }],
    ["Change image after:", { it: "Cambia immagine dopo:", zh: "在以下时间后更改图像：" }],
    ["Customize the output of the video:", { it: "Personalizza l'output del video:", zh: "自定义视频输出：" }],
    ["Video customization:", { it: "Personalizzazione del video:", zh: "视频自定义：" }],
    ["Font", { it: "Carattere", zh: "字体" }],
    ["Use a custom background image", { it: "Utilizza un'immagine personalizzata per lo sfondo", zh: "使用自定义背景图片" }],
    ["Scale", { it: "Scala", zh: "缩放" }],
    ["Video content:", { it: "Contenuto del video:", zh: "视频内容：" }],
    ["Show album art", { it: "Mostra la copertina dell'album", zh: "显示专辑封面" }],
    ["Show essential metadata information", { it: "Mostra le informazioni essenziali dai metadati", zh: "显示基本元数据信息" }],
    ["Show all metadata information", { it: "Mostra tutte le informazioni dei metadati", zh: "显示所有元数据信息" }],
    ["Show the selected custom background image", { it: "Mostra l'immagine di sfondo personalizzata", zh: "显示选定的自定义背景图片" }],
    ["Troubleshooting:", { it: "Risoluzione dei problemi:", zh: "故障排除：" }],
    ["Save temporary images on device", { it: "Salva le immagini temporanee sul dispositivo", zh: "在设备上保存临时图像" }],
    ["Disable 0.11.x only for this section (it might be unstable)", { it: "Disabilita 0.11.x per questa sezione (potrebbe essere instabile)", zh: "仅在此部分禁用 0.11.x（可能不稳定）" }],
    ["Get loop from audio duration. Disable it if you're having issues with the length of the file.", { it: "Ottieni il loop dalla durata dell'audio. Disabilita quest'opzione nel caso dovessi aver problemi con la lunghezza del file.", zh: "根据音频时长获取循环。如果文件长度有问题，请禁用它" }],
    ["Set `max_interleave_delta` to 0. This *might* help fixing wrong timestamps in Matroska files.", { it: "Imposta `max_interleave_delta` su 0. Questo *potrebbe* aiutare a sistemare dei timestamp sbagliati nei file Matroska.", zh: "将 `max_interleave_delta` 设为 0。这可能有助于修复 Matroska 文件中的错误时间戳" }],
    ["Convert music file to video", { it: "Converti un file musicale ad un video", zh: "将音乐文件转换为视频" }],
    ["Music to video:", { it: "Musica a video:", zh: "音乐转视频：" }],
    ["Select the audio files. We'll use ffmpeg to fetch the album art and the metadata, and we'll create some images with them.", { it: "Seleziona i file audio. Useremo ffmpeg per ottenere la copertina dell'album ed i metadati, e creeremo alcune immagini con quelli.", zh: "选择音频文件。我们将使用 ffmpeg 获取专辑封面和元数据，并用它们创建一些图像" }],
    ["Output container (extension):", { it: "Contenitore di destinazione (estensione):", zh: "输出容器（扩展名）：" }],
    ["Output codecs:", { it: "Codec di destinazione:", zh: "输出编解码器：" }],
    ["It might be a good idea keeping the original audio and video file, but you can still choose the output codec, and its bitrate", { it: "Può essere una buona idea tenere la sorgente originale per il file audio e video, ma puoi comunque scegliere il codec di destinazione, ed il suo bitrate", zh: "保留原始音频和视频文件可能是个好主意，但您仍然可以选择输出编解码器及其比特率" }],
    ["Video bitrate:", { it: "Bitrate del video:", zh: "视频比特率：" }],
    ["Audio bitrate:", { it: "Bitrate dell'audio:", zh: "音频比特率：" }],
    ["Show advanced settings", { it: "Mostra impostazioni avanzate", zh: "显示高级设置" }],
    ["Video codec", { it: "Codec video", zh: "视频编解码器" }],
    ["Audio codec", { it: "Codec audio", zh: "音频编解码器" }],
    ["FPS (-1 for variable)", { it: "FPS (-1 per variabile)", zh: "FPS（-1 表示可变）" }],
    ["Restore presentation timestamps to START. This *might* help fixing wrong timestamps.", { it: "Reimposta presentation timestamps all'inizio. Questo *potrebbe* aiutare a sistemare i timestamp sbagliati.", zh: "将呈现时间戳重置为开始。这可能有助于修复错误的时间戳" }],
    ["Custom output container", { it: "Container di destinazione personalizzato", zh: "自定义输出容器" }],
    ["File extension:", { it: "Estensione del file:", zh: "文件扩展名：" }],
    ["Use WORKERFS for file writing operations. This helps reducing RAM usage.", { it: "Utilizza WORKERFS per le operazioni di scrittura del file. Questo aiuta a ridurre l'utilizzo della RAM.", zh: "使用 WORKERFS 进行文件写入操作。这有助于减少 RAM 使用" }],
    ["[Using JSZIP - might give errors on many files or large ones]", { it: "[Utilizzando JSZIP - potrebbe dare degli errori se si scelgono tanti file o pesanti]", zh: "[使用 JSZIP - 可能在处理大量或大型文件时出错]" }],
    ["[Using Zip.JS - recommended]", { it: "[Utilizzando Zip.JS - consigliato]", zh: "[使用 Zip.JS - 推荐]" }],
    ["Use AudioToolbox encoder when choosing standard AAC (not libfdk_aac) and ALAC audio codecs. Available only on macOS.", { it: "Utilizza l'encoder AudioToolbox quando si sceglie AAC (non libfdk_aac) o ALAC come codec audio. Disponibile solo su macOS.", zh: "选择标准 AAC（非 libfdk_aac）和 ALAC 音频编解码器时使用 AudioToolbox 编码器。仅在 macOS 上可用" }]
])
/**
 * Translate a string
 * @param str the string to translate
 * @returns the translated string, if available
 */
export function getLang(str: string) {
    const translation = translations.get(str);
    return translation ? translation[(localStorage.getItem("ffmpegWeb-SelectedLanguage") as null | "it" | "zh") ?? navigator.language?.substring(0, 2) as "it" | "zh"] ?? str : str;
}